// This file is generated by kconfig_compiler from kmancala.kcfg.
// All changes you do to this file will be lost.

#include "kmancalaprefs.h"

#include <kglobal.h>
#include <QtCore/QFile>

class kMancalaPrefsHelper
{
  public:
    kMancalaPrefsHelper() : q(0) {}
    ~kMancalaPrefsHelper() { delete q; }
    kMancalaPrefs *q;
};
K_GLOBAL_STATIC(kMancalaPrefsHelper, s_globalkMancalaPrefs)
kMancalaPrefs *kMancalaPrefs::self()
{
  if (!s_globalkMancalaPrefs->q) {
    new kMancalaPrefs;
    s_globalkMancalaPrefs->q->readConfig();
  }

  return s_globalkMancalaPrefs->q;
}

kMancalaPrefs::kMancalaPrefs(  )
  : KConfigSkeleton( QLatin1String( "kmancalarc" ) )
{
  Q_ASSERT(!s_globalkMancalaPrefs->q);
  s_globalkMancalaPrefs->q = this;
  setCurrentGroup( QLatin1String( "Preferences" ) );

  KConfigSkeleton::ItemColor  *itemCol_background;
  itemCol_background = new KConfigSkeleton::ItemColor( currentGroup(), QLatin1String( "col_background" ), mCol_background, QColor( "black" ) );
  addItem( itemCol_background, QLatin1String( "col_background" ) );
  KConfigSkeleton::ItemColor  *itemCol_foreground;
  itemCol_foreground = new KConfigSkeleton::ItemColor( currentGroup(), QLatin1String( "col_foreground" ), mCol_foreground, QColor( "yellow" ) );
  addItem( itemCol_foreground, QLatin1String( "col_foreground" ) );
  KConfigSkeleton::ItemInt  *itemVal_time;
  itemVal_time = new KConfigSkeleton::ItemInt( currentGroup(), QLatin1String( "val_time" ), mVal_time, 2 );
  addItem( itemVal_time, QLatin1String( "val_time" ) );
}

kMancalaPrefs::~kMancalaPrefs()
{
  if (!s_globalkMancalaPrefs.isDestroyed()) {
    s_globalkMancalaPrefs->q = 0;
  }
}

